export const defalutDeviceList = [
  {deviceName: '手环-运动', deviceCode: 'ky.stl.Band.steps', index: 0},
  {deviceName: '手环-血压', deviceCode: 'ky.stl.Band.bloodpressure', index: 1},
  {deviceName: '手环-血氧', deviceCode: 'ky.stl.Band.bloodoxygen', index: 2},
  {deviceName: '手环-心率', deviceCode: 'ky.stl.Band.heartRate', index: 3},
  {deviceName: '手环-睡眠', deviceCode: 'ky.stl.Band.sleep', index: 4},
  {deviceName: '报告单-体成分', deviceCode: 'ky.stl.bgd.tcf', index: 5},
  {deviceName: '水杯数据', deviceCode: 'ky.stl.Water', index: 6},
  {deviceName: '量表-睡眠', deviceCode: 'ky.stl.diagnose-sleepTime', index: 7},
  {deviceName: '档案-身高体重', deviceCode: 'ky.stl.diagnose-wh', index: 8},
  {deviceName: '档案-身高体重', deviceCode: 'ky.stl.diagnose-wh', index: 9},
  {deviceName: '量表-运动', deviceCode: 'ky.stl.diagnose-outdoor', index: 10},
  {deviceName: '量表-心率', deviceCode: 'ky.stl.diagnose-heart', index: 11},
  {deviceName: '膳食营养-能量', deviceCode: 'ky.stl.cf.tjsp.ld-Energy', index: 12},
  {deviceName: '膳食营养-蛋白质', deviceCode: 'ky.stl.cf.tjsp.ld-Protein', index: 13},
  {deviceName: '膳食营养-脂肪', deviceCode: 'ky.stl.cf.tjsp.ld-Fat', index: 14},
  {deviceName: '膳食营养-碳水化合物', deviceCode: 'ky.stl.cf.tjsp.ld-Cho', index: 15},
  {deviceName: '儿童健康检查-运动', deviceCode: 'ky.stl.form.Y3D5YA9ZUQNW11IXEALFHQ2JKL6ERH1C-jk_tyhd', index: 16},
  {deviceName: '儿童健康检查-饮水量', deviceCode: 'ky.stl.form.Y3D5YA9ZUQNW11IXEALFHQ2JKL6ERH1C-jk_ysl', index: 17},
  {deviceName: '儿童健康检查-睡眠', deviceCode: 'ky.stl.form.Y3D5YA9ZUQNW11IXEALFHQ2JKL6ERH1C-jk_smsj', index: 18},
  {deviceName: '儿童健康检查-心率', deviceCode: 'ky.stl.form.Y3D5YA9ZUQNW11IXEALFHQ2JKL6ERH1C-jk_xl', index: 19},
  {deviceName: '儿童健康检查-BMI', deviceCode: 'ky.stl.form.Y3D5YA9ZUQNW11IXEALFHQ2JKL6ERH1C-jk_bmi', index: 20},
]
