server:
  port: 8090
  servlet:
    context-path: '/web/v1'

spring:
  data:
    mongodb:
      uri: mongodb://db_kangyu:db_kangyu_11@localhost:27017/stl_yunqi?authSource=db_kangyu&authMechanism=SCRAM-SHA-1
  aop:
    proxy-target-class: true

#spring.data.mongodb.uri=mongodb://user:pwd@ip1:port1,ip2:port2/database  多个节点集群配置
logging:
  file: D:/logs/logs.log
  level:
    root: info
    org:
      springframework:
        data:
          mongodb:
            core: debug
